--Bilgisayar Programcılığı
--1. Öğretim 2. Sınıf
-- Mehmet Ali Emiroğlu
-- 223010710022




--create database
CREATE DATABASE KUTUPHANE_PROJE;

-- create a table
CREATE TABLE UYELER (
  UYE_NO INT IDENTITY(1,1),
  UYE_ADI VARCHAR(20),
  UYE_SOYADI VARCHAR(20),
  CINSIYET VARCHAR(5),
  TELEFON VARCHAR(15),
  EPOSTA VARCHAR(40),
  SEHIR VARCHAR(30),
  PRIMARY KEY("UYE_NO")
);

CREATE TABLE ADRESLER (
    ADRES_NO INT IDENTITY(1,1),
    CADDE VARCHAR(20),
    MAHALLE VARCHAR(20),
    BINA_NO VARCHAR(20),
    SEHIR VARCHAR(20),
    POSTA_KODU INT,
    ULKE VARCHAR(20),
    PRIMARY KEY("ADRES_NO")
);

CREATE TABLE EMANET (
    EMANET_NO INT IDENTITY(1,1),
    ISBN VARCHAR(20) NOT NULL,
    UYE_NO INT NOT NULL,
    UYE_ADI VARCHAR(30) NOT NULL,
    UYE_SOYADI VARCHAR(50) NOT NULL,
    KUTUPHANE_NO INT NOT NULL,
    EMANET_TARIHI DATE,
    TESLIM_TARIHI DATE,
    KUTUPHANE_ADI VARCHAR(50),
    PRIMARY KEY("EMANET_NO") 
);

CREATE TABLE KITAPLAR (
    ISBN VARCHAR(20),
    KITAP_ADI VARCHAR(20),
    YAYIN_TARIHI VARCHAR(20),
    S_SAYISI INT,
    PRIMARY KEY("ISBN")
);

CREATE TABLE YAZARLAR (
    YAZAR_NO INT IDENTITY(1,1),
    YAZAR_ADI VARCHAR(20),
    YAZAR_SOYADI VARCHAR(20),
    PRIMARY KEY("YAZAR_NO")
);

CREATE TABLE KATEGORILER (
    KATEGORI_NO INT IDENTITY(1,1),
    KATEGORI_ADI VARCHAR(20),
    PRIMARY KEY("KATEGORI_NO")
);

CREATE TABLE KUTUPHANE (
    KUTUPHANE_NO INT IDENTITY(1,1),
    KUTUPHANE_ADI VARCHAR(20),
    ACIKLAMA VARCHAR(20),
    ADRES_NO INT,
    PRIMARY KEY("ADRES_NO")
);

CREATE TABLE KITAP_KUTUPHANE (
    KUTUPHANE_NO INT NOT NULL,
    ISBN VARCHAR(20) NOT NULL,
    MIKTAR INT
);


CREATE TABLE KITAP_KATEGORI (
    ISBN VARCHAR(20) NOT NULL,
    KATEGORI_NO INT NOT NULL
);

INSERT INTO UYELER VALUES(1,'Ahmet','Demir','Erkek','05357672954','abc@mail.com','Kayseri');
INSERT INTO ADRESLER VALUES(1,'Papatya','Esenyurt','37','Adana',38001,'Türkiye');
INSERT INTO KUTUPHANE VALUES(1,'Merkez','Merkez kütüphane',23);
INSERT INTO EMANET VALUES(1,'5674325679',1,1,'Seher','Güler',10-10-2023,12-12-2023,'Merkez kütüphane');
INSERT INTO KITAPLAR VALUES('5674325679','Algoritma Ve Programlamaya Giriş',05-05-2009,571);
INSERT INTO YAZARLAR VALUES(1,'Seçkin','Görür');
INSERT INTO KATEGORILER VALUES(1,'Programlama');
INSERT INTO KITAP_KUTUPHANE VALUES(1,'5674325679',130);

--soru3
SELECT * FROM UYELER ORDER BY UYE_NO ASC;

--soru4
SELECT * FROM EMANET WHERE EMANET_TARIHI > '01-01-2023';

--soru5
SELECT * FROM UYELER WHERE SEHIR='Kayseri' AND TELEFON LIKE '%6';

--soru6
SELECT * FROM EMANET WHERE DATEIF(TESLIM_TARIHI, NOW()) < 30;

--soru7
SELECT CONCAT(LEFT(UYE_ADI,1),LEFT(UYE_SOYADI,5)) AS BIRLESIK FROM UYELER WHERE LENGTH(UYE_SOYADI>5) ORDER BY BIRLESIK;

--soru8
SELECT COUNT(*) AS alinanemanetsayisi FROM EMANET WHERE YEAR(EMANET_TARIHI)=2020;

--soru9
SELECT * FROM EMANET WHERE KUTUPHANE_ADI='Merkez kütüphane' AND DATEIF(EMANET_TARIHI,TESLIM_TARIHI)>180;

--soru10
SELECT COUNT(*) AS secilen_sehirde_yasayanlar FROM UYELER WHERE SEHIR='Eskişehir';

--soru11
SELECT YAZAR_ADI FROM KITAPLAR WHERE YEAR(NOW()-YEAR(YAYIN_TARIHI)) >3;

--soru12
-en uzun
SELECT DATEIF(TESLIM_TARIHI,EMANET_TARIHI) AS en_uzun_sure FROM EMANET ORDER BY en_uzun_sure DESC LIMIT 1;

-en kısa
SELECT DATEIF(TESLIM_TARIHI,EMANET_TARIHI) AS en_kisa_sure FROM EMANET ORDER BY en_kisa_sure ASC LIMIT 1;

--soru13
SELECT UYE_NO,UYE_ADI,UYE_SOYADI FROM EMANET;
